services:
  grant_ros_container:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2_foxy_grant
    container_name: ros2_foxy_container
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      - /dev/bus/usb:/dev/bus/usb
    # volumes:
    #   - ./src:/apps/ros2_ws/src