services:
  grant_ros_container:
    build:
      context: .
      dockerfile: Dockerfile
    image: jetson-ros2-pytorch
    container_name: jetson-ros2-pytorch-container
    network_mode: host
    restart: unless-stopped
    privileged: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility