# Состояние объекта
# Например: Включить камеру - true, отключить камеру - false
bool state
---
# Статус изминения объекта: true - состояние успешно изменено, false - состояние не возможно было изменит
bool status
# Информация об изминении состояния
string msg